name: Build Dev Container Image

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image and push to registry
        uses: devcontainers/ci@v0.3
        with:
          imageName: kaniska487/myrepo
          imageTag: ${{ inputs.tag }}
          push: always
          subFolder: src